---
# tasks file for php-rhel

- name: Install PHP 8.0 in RHEL
  shell: dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
- name: Step 2
  shell: dnf install -y  http://rpms.remirepo.net/enterprise/remi-release-8.rpm
- name: Step 3
  shell: dnf module reset php
- name: Step 4
  shell: dnf module install -y php:remi-8.0
- name: Step 5
  shell: dnf install -y php-{mysqlnd,xml,xmlrpc,curl,gd,imagick,mbstring,opcache,soap,zip}
- name: Restart Httpd
  shell: systemctl restart httpd
