---
- name: Update server, disable firewall and disable SELinux
  import_playbook: ../static-assignments/update.yml hostlist=webserver-ansible

- name: Install Git
  import_playbook: ../static-assignments/common.yml hostlist=webserver-ansible

- name: Set up tooling webserver
  import_playbook: ../static-assignments/webservers.yml hostlist=webserver-ansible

- name: Install RHEL PHP
  import_playbook: ../static-assignments/php-rhel.yml hostlist=webserver-ansible

- name: Import dynamic variables
  import_playbook: ../dynamic-assignments/env-vars.yml hostlist=all
  tags:
    - always

- name: Install MySQl DB
  import_playbook: ../static-assignments/mysqldb.yml hostlist=db-ansible

- name: Setup LB
  import_playbook: ../static-assignments/loadbalancers.yml hostlist=lb-ansible
  when: load_balancer_is_required

- name: Install Let's Encrypt on load balancer 
  import_playbook: ../static-assignments/letsencrypt.yml hostlist=lb-ansible
