name: delete branches
on:
  push:
    branches:
      - main
      
env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  delete_merged_branches:
    runs-on: ubuntu-latest

    steps:
      # This will set some environment variables from vault keys.
      - uses: actions/checkout@v2
      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.TEST_SECRET }}
      #     known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Delete branches 
        working-directory: testdir
        run: |
          # Github's ubuntu job runner has no SSH configurations, so you need to manually start 'ssh-agent'
          # to help you with the SSH commands. You will have to create .ssh directory in the repo and add an empty
          # file named 'config' (this is used for silently ignoring the authenticity of github.com) inside.
          ## eval "$(ssh-agent -s)"
          # actions/checkout@v2 already has added the remote repository, so no need for 'git remote add...'
          # git remote add origin git@github.com:osygroup/ansible-config-mgt.git
          ## echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> .ssh/config
          chmod +x delete_branch.sh
          bash delete_branch.sh
