name: test repository dispatch
on:
  workflow_dispatch:
  push:
    branches:
      - feature-001

jobs:
  test_repository_dispatch:
    runs-on: ubuntu-latest
    #if: contains(github.ref, 'feature-')  #this job will run if the github ref contains 'feature-' in the name of the branch that triggers the workflow
    #if: github.ref == 'refs/heads/feature-001'   #this job will run if the name of the branch that triggers the workflow is equal to feature-001
    #if: branch == 'feature-001' #
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - run: |
          echo ENV=preprod >> $GITHUB_ENV
          echo MYNAME=OSY
          echo $MYNAME | name

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "myname": "ERNESTO", "region": "eu-west-1", "BRANCH": "${{ steps.extract_branch.outputs.branch }}", "ENV": "${{ env.ENV }}"}, "name": "${{ name }}'
