  
name: List objects in S3
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
  push:
    branches:
      - main
      - feature-001

jobs:
  list_objects_in_s3_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Config AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-region: ${{ github.event.client_payload.region }} #eu-west-1
          aws-region: eu-west-1
          
      - name: Branch used
        id: extract_branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "::set-output name=branch::$(echo $GITHUB_BASE_REF)"
          else
            echo "::set-output name=branch::INVALID_EVENT_BRANCH_UNKNOWN"
          fi

      - name: List objects in s3 bucket  
        run: |
          #aws s3 rm s3://plutotv-tf-state/transcode/us-east1 --recursive --exclude "ste/ste_vault/terraform.tfstate" --dryrun
          #aws s3 ls s3://plutotv-tf-state/transcode/us-east1
          aws s3 ls s3://oscorp --recursive
          echo ${{ github.event.client_payload.sha }}
          echo ${{ github.event.client_payload.myname }}
          echo ${{ github.ref }}
          echo ${{ steps.extract_branch.outputs.branch }}
          echo $GITHUB_EVENT_PATH
