  
name: List objects in S3
on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:
  push:
    branches:
      - main
      - feature-001

jobs:
  list_objects_in_s3_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Config AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-region: ${{ github.event.client_payload.region }} #eu-west-1
          aws-region: eu-west-1

      - name: List objects in s3 bucket  
        run: |
          #aws s3 rm s3://plutotv-tf-state/transcode/us-east1 --recursive --exclude "ste/ste_vault/terraform.tfstate" --dryrun
          #aws s3 ls s3://plutotv-tf-state/transcode/us-east1
          aws s3 ls s3://oscorp --recursive
          echo ${{ github.event.client_payload.sha }}
          echo ${{ github.event.client_payload.myname }}
          echo ${{ github.ref }}
          #echo ${GITHUB_REF#refs/heads/}
          echo ${{ github.event.client_payload.ref }}
          echo ${{ github.event.client_payload.BRANCH }}
          #cat /home/runner/work/_temp/_github_workflow/event.json
          
          #if [[ ${{ github.event.client_payload.BRANCH }} = "feature-001" ]]
          if [[ ${{ github.event.client_payload.BRANCH }} = "feature-001" ]]
          then
            echo ENVIRONMENT=dev >> $GITHUB_ENV
          else
            eho ENVIRONMENT=preprod >> $GITHUB_ENV
          fi
          

      - name: Repository Dispatch testin
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "myname": "ERNESTO", "ENV": "${{ env.ENVIRONMENT }}"}'
